/*
 * therapeutic_theme.h — CSS ТЕМА ДЛЯ GTK
 *
 * Рожевий. Comic Sans якби міг. Золоті кнопки.
 * Best viewed у стані екзистенційної кризи.
 *
 * Клієнт. Зрозуміло.
 */

#ifndef THERAPEUTIC_THEME_H
#define THERAPEUTIC_THEME_H

/* Це не CSS. Це візуальне вираження внутрішнього болю. */
static const char *THERAPEUTIC_CSS =
    "/* Спокій — це не коли CSS валідний. */\n"
    "\n"
    "window {\n"
    "  background: linear-gradient(180deg, #FF69B4, #FF1493, #C71585);\n"
    "}\n"
    "\n"
    "#main-box {\n"
    "  padding: 20px;\n"
    "}\n"
    "\n"
    "#title-label {\n"
    "  font-size: 28px;\n"
    "  font-weight: bold;\n"
    "  color: #FFD700;\n"
    "  text-shadow: 2px 2px #FF0000;\n"
    "  margin-bottom: 10px;\n"
    "}\n"
    "\n"
    "#subtitle-label {\n"
    "  font-size: 14px;\n"
    "  color: #FFFFFF;\n"
    "  font-style: italic;\n"
    "  margin-bottom: 15px;\n"
    "}\n"
    "\n"
    "#wisdom-view {\n"
    "  font-size: 16px;\n"
    "  color: #2D0033;\n"
    "  background-color: #FFF0F5;\n"
    "  border: 3px solid #FFD700;\n"
    "  border-radius: 10px;\n"
    "  padding: 15px;\n"
    "}\n"
    "\n"
    "#wisdom-view text {\n"
    "  color: #2D0033;\n"
    "  background-color: #FFF0F5;\n"
    "}\n"
    "\n"
    "#generate-button {\n"
    "  background: linear-gradient(180deg, #FFD700, #FFA500);\n"
    "  color: #8B0000;\n"
    "  font-size: 18px;\n"
    "  font-weight: bold;\n"
    "  border-radius: 25px;\n"
    "  padding: 12px 30px;\n"
    "  border: 3px solid #FF4500;\n"
    "  margin: 10px;\n"
    "  min-height: 50px;\n"
    "}\n"
    "\n"
    "#generate-button:hover {\n"
    "  background: linear-gradient(180deg, #FFFF00, #FFD700);\n"
    "  border-color: #FF0000;\n"
    "}\n"
    "\n"
    "#copy-button {\n"
    "  background: linear-gradient(180deg, #9370DB, #8A2BE2);\n"
    "  color: #FFFFFF;\n"
    "  font-size: 14px;\n"
    "  font-weight: bold;\n"
    "  border-radius: 15px;\n"
    "  padding: 8px 20px;\n"
    "  border: 2px solid #FFD700;\n"
    "}\n"
    "\n"
    "#copy-button:hover {\n"
    "  background: linear-gradient(180deg, #BA55D3, #9370DB);\n"
    "}\n"
    "\n"
    "#mode-combo {\n"
    "  font-size: 14px;\n"
    "  background-color: #FFF0F5;\n"
    "  color: #8B008B;\n"
    "  border: 2px solid #FFD700;\n"
    "  border-radius: 8px;\n"
    "  padding: 5px;\n"
    "  min-height: 35px;\n"
    "}\n"
    "\n"
    "#streak-label {\n"
    "  font-size: 12px;\n"
    "  color: #FFD700;\n"
    "  font-style: italic;\n"
    "}\n"
    "\n"
    "#mood-label {\n"
    "  font-size: 13px;\n"
    "  color: #FFFFFF;\n"
    "  font-style: italic;\n"
    "}\n"
    "\n"
    "#counter-label {\n"
    "  font-size: 11px;\n"
    "  color: #FFC0CB;\n"
    "}\n"
    "\n"
    "#footer-label {\n"
    "  font-size: 10px;\n"
    "  color: #FFB6C1;\n"
    "  margin-top: 10px;\n"
    "}\n";

#endif /* THERAPEUTIC_THEME_H */
